version: '3.8'
services:
  backend:
    network_mode: backend
    build:
      context: .
      target: backend-stage
    working_dir: /app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend

  frontend:
    build:
      context: .
      target: frontend-stage
    working_dir: /app/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: npm run dev -- --host --port 3000
    environment:
      - VITE_SERVER_URL= backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/frontend

networks:
  default:
    name: cataloger-net
