version: '3.8'
services:
  backend:
    build:
      context: .
      target: backend-stage
    working_dir: /app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000

networks:
  default:
    name: cataloger-net
