version: '3.8'
services:
  backend:
    build:
      context: .
      target: backend-stage
    working_dir: /app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    entrypoint: ["/bin/bash", "entrypoint.sh"]
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend

networks:
  default:
    name: cataloger-net
